# Generated by Django 2.0.5 on 2018-05-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(default=''),
        ),
    ]
